# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-Authentication-Simple
version:      1.00
version_from: lib/Catalyst/Plugin/Authentication/Simple.pm
installdirs:  site
requires:
    Catalyst:                      2.99
    Catalyst::Plugin::Session::FastMmap: 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
